# Generated by Django 6.0 on 2026-01-03 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('correct_guess', 'Correct guess'), ('unguessed_song', 'Unguessed song')], max_length=32)),
                ('points', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='game.room')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='game.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoundSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_songs', to='game.round')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='round_song', to='game.songsubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('round', 'order_index'), name='uniq_round_order_index')],
            },
        ),
    ]
